### ISSUE TITLE
Full screen does not work

### ISSUE THREAD

**Issue by AmirHosein-Gharaati** [ar-ekt/Snake#1]
After running the game, the full screen became like this.

![image](https://user-images.githubusercontent.com/56169125/92905420-e07f3380-f438-11ea-8b10-6201b29a71e1.png)

Tried changing the tabs, and then using the game screen, I faced this:

![image](https://user-images.githubusercontent.com/56169125/92905928-51265000-f439-11ea-9be0-c73e8a649d09.png)

But the main is:
![](https://user-images.githubusercontent.com/57006850/92823654-c9155b80-f3e2-11ea-9d86-cb619f7baae6.gif)

**Comment by ar-ekt** [comment]
Currently the game only supports 1920x1080 screen.
I'll try to make the game support more screens.

**Comment by AmirHosein-Gharaati** [comment]
Strange !

Currently, I am using 1920*1080 resolution on my laptop, and I faced this problem.

**Comment by ar-ekt** [comment]
I think the problem has been fixed, try again.

**Comment by AmirHosein-Gharaati** [comment]
Found the reason of error !

I set my resolution scale to 125%, then changed to 100% and screen worked fine.

But after all, it would be nice if your game works for all screen resolutions and scales.
